services:
  meme-webapp:
    image: ghcr.io/hakaczu/meme-webapp:master
    ports:
      - "5050:5050"
    environment:
      - FLASK_DEBUG=false
    volumes:
      - meme_stats:/meme-app/data
    restart: unless-stopped

volumes:
  meme_stats:
